name: EBBR and SBBR Daily build

on:
  schedule:
    - cron: '30 17 * * *'
  workflow_dispatch:

jobs:
  build_image:
    name: Build EBBR and SBBR images
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        env:
        - ARCH: x86_64
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - name: Checkout BBR repository
      uses: actions/checkout@v4
      with:
        path: 'bbr-acs'
    - name: Get required source codes and tools for EBBR
      run: |
        cd bbr-acs/ebbr/scripts  
        ./build-scripts/get_ebbr_source.sh  
    - name: Build EBBR
      run: |
        cd bbr-acs/ebbr/scripts 
        ./build-scripts/build_ebbr.sh
    - name: Create EBBR-SCT.zip
      run: |
        cd bbr-acs/ebbr/scripts/edk2-test/uefi-sct/EBBR-SCT
        zip -r ../EBBR-SCT.zip .
    - name: Validate EBBR-SCT.zip exists
      run: |
        if [ ! -f "bbr-acs/ebbr/scripts/edk2-test/uefi-sct/EBBR-SCT.zip" ]; then
          echo "ERROR: EBBR-SCT.zip missing!"
          exit 1
        fi
    - name: Upload EBBR-SCT.zip as an artifact
      uses: actions/upload-artifact@v4
      with:
          name: EBBR-SCT
          path: bbr-acs/ebbr/scripts/edk2-test/uefi-sct/EBBR-SCT.zip
          if-no-files-found: error   
    - name: Check for CapsuleApp.efi (EBBR)
      run: |
        if [ ! -e "bbr-acs/ebbr/scripts/edk2/Build/MdeModule/DEBUG_GCC5/AARCH64/CapsuleApp.efi" ]; then
          echo "CapsuleApp.efi not found for EBBR, raising an error."
          exit 1
        fi
    - name: Get required source codes and tools for SBBR
      run: |
        cd $GITHUB_WORKSPACE  # Go back to the root directory of the repository
        cd bbr-acs/sbbr/scripts
        ./build-scripts/get_sbbr_source.sh
    - name: Build SBBR
      run: |
        cd bbr-acs/sbbr/scripts
        ./build-scripts/build_sbbr.sh
    - name: Create SBBR-SCT.zip
      run: |
        cd bbr-acs/sbbr/scripts/edk2-test/uefi-sct/SBBR-SCT
        zip -r ../SBBR-SCT.zip .
    - name: Validate SBBR-SCT.zip exists
      run: |
        if [ ! -f "bbr-acs/sbbr/scripts/edk2-test/uefi-sct/SBBR-SCT.zip" ]; then
          echo "ERROR: SBBR-SCT.zip missing!"
          exit 1
        fi
    - name: Upload SBBR-SCT.zip as an artifact
      uses: actions/upload-artifact@v4
      with:
          name: SBBR-SCT
          path: bbr-acs/sbbr/scripts/edk2-test/uefi-sct/SBBR-SCT.zip
          if-no-files-found: error   
    - name: Check for CapsuleApp.efi (SBBR)
      run: |
        if [ ! -e "bbr-acs/sbbr/scripts/edk2/Build/MdeModule/DEBUG_GCC5/AARCH64/CapsuleApp.efi" ]; then
          echo "CapsuleApp.efi not found for SBBR, raising an error."
          exit 1
        fi
    - name: Get required source codes and tools for Standalone FWTS
      run: |
        cd $GITHUB_WORKSPACE  # Go back to the root directory of the repository
    - name: Build FWTS
      run: |
        cd bbr-acs
        ./common/scripts/build-standalone-fwts.sh
    - name: Check for FWTS outout
      run: |
        if [ ! -e "bbr-acs/fwts_workspace/buildroot/output/target/usr/bin/fwts" ]; then
          echo "FWTS bin not found, raising an error."
          exit 1
        else
          cd bbr-acs/fwts_workspace/
          mkdir -p fwts/bin
          cp buildroot/output/target/usr/bin/fwts fwts/bin
          mkdir -p fwts/lib
          mkdir -p fwts/lib64
          mkdir -p fwts/share
          cp -r buildroot/output/target/usr/lib64/fwts/* fwts/lib64
          cp -r buildroot/output/target/usr/lib/fwts/* fwts/lib
          cp -r buildroot/output/target/usr/share/fwts/* fwts/share   
          cd -
        fi
    - name: Save FWTS.zip as an artifact
      uses: actions/upload-artifact@v4
      with:
          name: FWTS
          path: bbr-acs/fwts_workspace/fwts/
          if-no-files-found: error
